export const Images = {
  logo: require('./images/LogoBG.png'),
  waves: require('./images/waves.png'),
  land1: require('./images/land1.png'),
  land2: require('./images/land2.png'),
  profileicon: require('./images/profileicon.png'),
  scanner: require('./images/scanner.png'),
  secure: require('./images/secure.png'),
  assets: require('./images/assets.png'),
  explore: require('./images/explore.png'),
  home: require('./images/home.png'),
  trade: require('./images/trade.png'),
  down:require('./images/down.png'),
  buy : require('./images/buy.png'),
  earn : require('./images/earn.png'),
  recieve : require('./images/recieve.png'),
  send : require('./images/send.png'),
  coinlogo : require('./images/coinlogo.png'),
  tradelogo : require('./images/trade.png'),
  pros: require('./images/pros.png'),
 cross:require('./images/cross.png')
}
